name: restful
version: 0.1.0
author: Sergey Akopkokhyants <akserg@gmail.com>
description: Restful is a library built specifically to enable you to build correct REST web services on Dart.
homepage: https://github.com/akserg/restful
dependencies:
  unittest: any